# Generated by Django 4.0.3 on 2022-04-24 00:17

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('manufacturer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'manufacturer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('m_id', models.CharField(default=api.models.generate_unique_code_member, max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('user_status', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateField()),
                ('billing_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orderlist',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
            ],
            options={
                'db_table': 'orderList',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('p_name', models.CharField(max_length=50)),
                ('wholesale_price', models.FloatField()),
                ('instore_price', models.FloatField()),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.manufacturer')),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shippingcompany',
            fields=[
                ('sc_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sc_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ShippingCompany',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('s_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'store',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('w_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'warehouse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Onlineorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer_type', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('card_info', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone_num', models.BigIntegerField()),
                ('recipient_name', models.CharField(max_length=30)),
                ('recipient_phone', models.BigIntegerField()),
                ('tracking_num', models.CharField(max_length=20)),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.member')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.orderlist')),
                ('p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
                ('sc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.shippingcompany')),
            ],
            options={
                'db_table': 'onlineOrder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Memberaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=15)),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.member')),
            ],
            options={
                'db_table': 'memberAddress',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instoreorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer_type', models.IntegerField(blank=True, null=True)),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.member')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.orderlist')),
                ('p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
                ('s', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.store')),
            ],
            options={
                'db_table': 'instoreOrder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Whcoverage',
            fields=[
                ('w', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.warehouse')),
                ('state', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'whCoverage',
                'managed': True,
                'unique_together': {('w', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Warehouseinv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('restock', models.DateField()),
                ('reorder', models.DateField()),
                ('p', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
                ('w', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.warehouse')),
            ],
            options={
                'db_table': 'warehouseINV',
                'managed': True,
                'unique_together': {('w', 'p')},
            },
        ),
        migrations.CreateModel(
            name='Storeinv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('restock', models.DateField()),
                ('reorder', models.DateField()),
                ('p', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
                ('s', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.store')),
            ],
            options={
                'db_table': 'storeINV',
                'managed': True,
                'unique_together': {('s', 'p')},
            },
        ),
        migrations.CreateModel(
            name='Membercardinfo',
            fields=[
                ('m', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.member')),
                ('card_num', models.CharField(max_length=20, unique=True)),
                ('card_name', models.CharField(max_length=30)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'memberCardInfo',
                'managed': True,
                'unique_together': {('m', 'card_num')},
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('card_num', models.ForeignKey(blank=True, db_column='card_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.membercardinfo')),
            ],
            options={
                'db_table': 'bank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Whstore',
            fields=[
                ('w', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.warehouse')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.store')),
            ],
            options={
                'db_table': 'whStore',
                'managed': True,
                'unique_together': {('w', 's')},
            },
        ),
        migrations.CreateModel(
            name='Warehousereorder',
            fields=[
                ('w', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.warehouse')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('reorderdate', models.DateField(db_column='reorderDate')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.manufacturer')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
            ],
            options={
                'db_table': 'warehouseReorder',
                'managed': True,
                'unique_together': {('w', 'p', 'reorderdate')},
            },
        ),
        migrations.CreateModel(
            name='Storereorder',
            fields=[
                ('s', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.store')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('reorderdate', models.DateField(db_column='reorderDate')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.product')),
                ('w', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.warehouse')),
            ],
            options={
                'db_table': 'storeReorder',
                'managed': True,
                'unique_together': {('s', 'p', 'reorderdate')},
            },
        ),
    ]
